#ifndef _TASKS_COMMOM_H_
#define _TASKS_COMMOM_H_

//Task Relógio
#define TASK_STACK_SIZE_RELOGIO       512
#define TASK_PRIORITY_RELOGIO         5

#define TASK_STACK_SIZE_SERIAL        4096
#define TASK_PRIORITY_SERIAL          4

#define TASK_STACK_SIZE_ALIMENTADOR   512
#define TASK_PRIORITY_ALIMENTADOR     3
#endif
